### ISSUE TITLE
UPyPlotController not found

### ISSUE THREAD

**Issue by siddie** [edualvarado/unity-antagonistic-controller#1]
Hey, @edualvarado Thank you for sharing the code.

I am trying to run the project and the build fails. I can see that UPyPlotController is referenced a lot. However, it is missing from the project. 

Is there something I am missing?

**Comment by edualvarado** [comment]
Hello,

UPyPlotController should not be necessary to build the project. It is just a Python module to plot different values in real-time using Matplotlib. Try commenting on all the PyPlot references before building. Let me know if it works.
